SUBDIRS = \
	src \
	$(NULL)

noinst_HEADERS = \
	include/osmocom/proxy/burst_fwd.h \
	include/osmocom/proxy/burst_synch.h \
	include/osmocom/proxy/clck_gen.h \
	include/osmocom/proxy/logging.h \
	include/osmocom/proxy/path_sim.h \
	include/osmocom/proxy/proxy.h \
	include/osmocom/proxy/trx.h \
	include/osmocom/proxy/vty.h \
	$(NULL)
